package Compilador.Gramatica.Tokens;

public enum PalavrasChaveEnums {
    PALAVRA_CHAVE_CLASS,
    PALAVRA_CHAVE_END_CLASS,
    PALAVRA_CHAVE_VARS,
    PALAVRA_CHAVE_METHOD,
    PALAVRA_CHAVE_BEGIN,
    PALAVRA_CHAVE_END,
    PALAVRA_CHAVE_END_METHOD,
    PALAVRA_CHAVE_NEW,
    PALAVRA_CHAVE_IF,
    PALAVRA_CHAVE_THEN,
    PALAVRA_CHAVE_ELSE,
    PALAVRA_CHAVE_END_IF,
    PALAVRA_CHAVE_RETURN,
    PALAVRAS_CHAVE_SELF,
    PALAVRAS_CHAVE_IO
}